
import pandas as pd

# ตั้งค่า Pandas
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.max_colwidth', None)
from app.Simulations.TransactionContext import TransactionContext


class SoapPayloadBuilder:
    """ทำหน้าที่สร้าง XML สำหรับยิง API ทุกรูปแบบ (แยกส่วนหน้าที่ชัดเจน ตามมาตรฐาน Enterprise)"""
    
    @staticmethod
    def build_data_exchange(tx: TransactionContext) -> str:
        return f"""<?xml version="1.0" encoding="UTF-8"?><HQ_REQUEST><SERVICE_BOX><ADDRESS><VENDOR_ID>{tx.store.vendor_id}</VENDOR_ID><SERVICE_ID>{tx.store.service_id}</SERVICE_ID><METHOD>DataExchange</METHOD></ADDRESS><DATA><PAYMENT_CHANNEL>{tx.store.payment_channel}</PAYMENT_CHANNEL><VENDOR_ID>{tx.store.vendor_id}</VENDOR_ID><SERV_ID>{tx.store.service_id}</SERV_ID><SERVICE_ID>{tx.store.service_id}</SERVICE_ID><STORE_ID>{tx.store.store_id}</STORE_ID><STATION_ID>1</STATION_ID><BUS_DATE>{tx.bus_date}</BUS_DATE><BUS_TIME>{tx.bus_time}</BUS_TIME><SYS_DATE>{tx.bus_date}</SYS_DATE><SYS_TIME>{tx.bus_time}</SYS_TIME><COMMON_TRN_ID>{tx.common_trn_id}</COMMON_TRN_ID><SEQ_NO></SEQ_NO><CLIENT_SERV_SEQ></CLIENT_SERV_SEQ><SHIFT_ID>9</SHIFT_ID><TRANS_TYPE>N</TRANS_TYPE><ACCT_NO></ACCT_NO><BILL_AMT>{tx.bill.bill_amt}</BILL_AMT><ROUND_BILL_AMT>{tx.bill.bill_amt}</ROUND_BILL_AMT><VAT_AMT>{tx.store.vat_amt}</VAT_AMT><REPT_TYPE>{tx.store.rept_type}</REPT_TYPE><REPT_NO></REPT_NO><PREV_REF_SEQ></PREV_REF_SEQ><PREV_REF_DATE></PREV_REF_DATE><SERV_CHARGE_NO></SERV_CHARGE_NO><ITEM_NAME>{tx.store.item_name}</ITEM_NAME><ITEM_SELECTION>N</ITEM_SELECTION><EMPLOYEE_ID>{tx.store.employee_id}</EMPLOYEE_ID><POS_TAX_ID>{tx.store.pos_tax_id}</POS_TAX_ID><DATA_1>{tx.data_1}</DATA_1><DATA_2>{tx.data_2}</DATA_2><DATA_3>{tx.data_3}</DATA_3><DATA_4>{tx.data_4}</DATA_4><DATA_5>{tx.data_5}</DATA_5><DATA_6>{tx.data_6}</DATA_6><DATA_7>{tx.data_7}</DATA_7><DATA_9>{tx.data_9}</DATA_9><ZONE>{tx.store.zone}</ZONE><PAYMENT_TYPE>001</PAYMENT_TYPE><CANCEL_ID></CANCEL_ID><CUST_NAME>{tx.customer.name}</CUST_NAME><CUST_ADDR_1>{tx.customer.addr_1}</CUST_ADDR_1><CUST_ADDR_2>{tx.customer.addr_2}</CUST_ADDR_2><CUST_ADDR_3>{tx.customer.addr_3}</CUST_ADDR_3><CUST_PHONE_NO>{tx.customer.phone_no}</CUST_PHONE_NO></DATA></SERVICE_BOX></HQ_REQUEST>"""

    @staticmethod
    def build_cancel(tx: TransactionContext) -> str:
        ref = tx.ref_data
        return f"""<?xml version="1.0" encoding="UTF-8"?><HQ_REQUEST><SERVICE_BOX><ADDRESS><VENDOR_ID>{tx.store.vendor_id}</VENDOR_ID><SERVICE_ID>{tx.store.service_id}</SERVICE_ID><METHOD>Cancel</METHOD></ADDRESS><DATA><PAYMENT_CHANNEL>{tx.store.payment_channel}</PAYMENT_CHANNEL><VENDOR_ID>{ref.get('VENDOR_ID', '')}</VENDOR_ID><SERV_ID>{ref.get('SERV_ID', '')}</SERV_ID><SERVICE_ID>{ref.get('SERV_ID', '')}</SERVICE_ID><STORE_ID>{tx.store.store_id}</STORE_ID><STATION_ID>1</STATION_ID><BUS_DATE>{tx.bus_date}</BUS_DATE><BUS_TIME>{tx.bus_time}</BUS_TIME><TX_ID>{ref.get('TX_ID', '')}</TX_ID><PAYMENT_TYPE>001</PAYMENT_TYPE><CANCEL_ID></CANCEL_ID></DATA></SERVICE_BOX></HQ_REQUEST>"""

    @staticmethod
    def build_data_exchange_confirm(tx: TransactionContext) -> str:
        ref = tx.ref_data
        return f"""<?xml version="1.0" encoding="UTF-8"?><HQ_REQUEST><SERVICE_BOX><ADDRESS><VENDOR_ID>{tx.store.vendor_id}</VENDOR_ID><SERVICE_ID>{tx.store.service_id}</SERVICE_ID><METHOD>DataExchangeConfirm</METHOD></ADDRESS><DATA><PAYMENT_CHANNEL>{tx.store.payment_channel}</PAYMENT_CHANNEL><VENDOR_ID>{ref.get('VENDOR_ID', '')}</VENDOR_ID><SERV_ID>{ref.get('SERV_ID', '')}</SERV_ID><SERVICE_ID>{ref.get('SERV_ID', '')}</SERVICE_ID><STATION_ID>1</STATION_ID><STORE_ID>{tx.store.store_id}</STORE_ID><BUS_DATE>{tx.bus_date}</BUS_DATE><BUS_TIME>{tx.bus_time}</BUS_TIME><SYS_DATE>{tx.bus_date}</SYS_DATE><SYS_TIME>{tx.bus_time}</SYS_TIME><TX_ID>{ref.get('TX_ID', '')}</TX_ID><SEQ_NO>{ref.get('SEQ_NO', '')}</SEQ_NO><EMPLOYEE_ID>{tx.store.employee_id}</EMPLOYEE_ID><CLIENT_SERV_SEQ>{ref.get('SEQ_NO', '')}</CLIENT_SERV_SEQ><SERV_ID>{tx.store.service_id}</SERV_ID><BILL_AMT>{ref.get('BILL_AMT', '')}</BILL_AMT><ROUND_BILL_AMT>{ref.get('BILL_AMT', '')}</ROUND_BILL_AMT><ACCT_NO></ACCT_NO><VAT_AMT>{tx.store.vat_amt}</VAT_AMT><DATA_1>{ref.get('DATA_1', '')}</DATA_1><DATA_2>{ref.get('DATA_2', '')}</DATA_2><DATA_3>{ref.get('DATA_3', '')}</DATA_3><DATA_4>{ref.get('DATA_4', '')}</DATA_4><DATA_5>{ref.get('DATA_5', '')}</DATA_5><DATA_6>{ref.get('DATA_6', '')}</DATA_6><DATA_7>{ref.get('DATA_7', '')}</DATA_7><DATA_9>{ref.get('DATA_9', '')}</DATA_9><ZONE>{tx.store.zone}</ZONE><PAYMENT_TYPE>001</PAYMENT_TYPE><TOT_BILL_TRANS></TOT_BILL_TRANS><TOT_BILL_AMT></TOT_BILL_AMT><TOT_VENDOR_TRANS></TOT_VENDOR_TRANS><TOT_VENDOR_AMT></TOT_VENDOR_AMT><TOT_COUNTER_TRANS></TOT_COUNTER_TRANS><TOT_COUNTER_AMT></TOT_COUNTER_AMT><TOT_CLIENT_TRANS></TOT_CLIENT_TRANS><TOT_CLIENT_AMT></TOT_CLIENT_AMT><TOT_BILL_TRANS_OR></TOT_BILL_TRANS_OR><TOT_BILL_AMT_OR></TOT_BILL_AMT_OR><CANCEL_ID></CANCEL_ID><CANCEL_ID></CANCEL_ID><CUST_NAME>{ref.get('CUST_NAME', '')}</CUST_NAME><CUST_ADDR_1>{ref.get('CUST_ADDR_1', '')}</CUST_ADDR_1><CUST_ADDR_2>{ref.get('CUST_ADDR_2', '')}</CUST_ADDR_2><CUST_ADDR_3>{ref.get('CUST_ADDR_3', '')}</CUST_ADDR_3><CUST_PHONE_NO>{ref.get('CUST_PHONE_NO', '')}</CUST_PHONE_NO></DATA></SERVICE_BOX></HQ_REQUEST>"""

    @staticmethod
    def build_print(tx: TransactionContext) -> str:
        ref = tx.ref_data
        return f"""<?xml version="1.0" encoding="UTF-8"?><HQ_REQUEST><SERVICE_BOX><ADDRESS><VENDOR_ID>{tx.store.vendor_id}</VENDOR_ID><SERVICE_ID>{tx.store.service_id}</SERVICE_ID><METHOD>REPRINTSLIP</METHOD></ADDRESS><DATA><PAYMENT_CHANNEL>{tx.store.payment_channel}</PAYMENT_CHANNEL><VENDOR_ID>{ref.get('VENDOR_ID', '')}</VENDOR_ID><SERV_ID>{ref.get('SERV_ID', '')}</SERV_ID><SERVICE_ID>{ref.get('SERV_ID', '')}</SERVICE_ID><STORE_ID>{tx.store.store_id}</STORE_ID><STATION_ID>1</STATION_ID><BUS_DATE>{tx.bus_date}</BUS_DATE><BUS_TIME>{tx.bus_time}</BUS_TIME><COMMON_TRN_ID>{tx.common_trn_id}</COMMON_TRN_ID><SEQ_NO>{ref.get('SEQ_NO', '')}</SEQ_NO><CLIENT_SERV_SEQ>{ref.get('SEQ_NO', '')}</CLIENT_SERV_SEQ><SHIFT_ID>9</SHIFT_ID><TRANS_TYPE>N</TRANS_TYPE><ACCT_NO></ACCT_NO><BILL_AMT>{ref.get('BILL_AMT', '')}</BILL_AMT><ROUND_BILL_AMT>{ref.get('BILL_AMT', '')}</ROUND_BILL_AMT><VAT_AMT>{tx.store.vat_amt}</VAT_AMT><REPT_TYPE>{tx.store.rept_type}</REPT_TYPE><TX_ID>{ref.get('TX_ID', '')}</TX_ID><REPT_NO></REPT_NO><PREV_REF_SEQ></PREV_REF_SEQ><PREV_REF_DATE></PREV_REF_DATE><SERV_CHARGE_NO></SERV_CHARGE_NO><ITEM_NAME>{tx.store.item_name}</ITEM_NAME><ITEM_SELECTION>N</ITEM_SELECTION><EMPLOYEE_ID>{tx.store.employee_id}</EMPLOYEE_ID><POS_TAX_ID>{tx.store.pos_tax_id}</POS_TAX_ID><DATA_1>{ref.get('DATA_1', '')}</DATA_1><DATA_2>{ref.get('DATA_2', '')}</DATA_2><DATA_3>{ref.get('DATA_3', '')}</DATA_3><DATA_4>{ref.get('DATA_4', '')}</DATA_4><DATA_5>{ref.get('DATA_5', '')}</DATA_5><DATA_6>{ref.get('DATA_6', '')}</DATA_6><DATA_7>{ref.get('DATA_7', '')}</DATA_7><DATA_9>{ref.get('DATA_9', '')}</DATA_9><ZONE>{tx.store.zone}</ZONE><CANCEL_ID></CANCEL_ID></DATA></SERVICE_BOX></HQ_REQUEST>"""

    @staticmethod
    def build_or(tx: TransactionContext) -> str:
        ref = tx.ref_data
        return f"""<?xml version="1.0" encoding="UTF-8"?><HQ_REQUEST><SERVICE_BOX><ADDRESS><VENDOR_ID>{tx.store.vendor_id}</VENDOR_ID><SERVICE_ID>{tx.store.service_id}</SERVICE_ID><METHOD>OR</METHOD></ADDRESS><DATA><PAYMENT_CHANNEL>{tx.store.payment_channel}</PAYMENT_CHANNEL><VENDOR_ID>{ref.get('VENDOR_ID', '')}</VENDOR_ID><SERVICE_ID>{ref.get('SERV_ID', '')}</SERVICE_ID><SERV_ID>{ref.get('SERV_ID', '')}</SERV_ID><STORE_ID>{tx.store.store_id}</STORE_ID><STATION_ID>1</STATION_ID><BUS_DATE>{tx.bus_date}</BUS_DATE><BUS_TIME>{tx.bus_time}</BUS_TIME><SYS_DATE>{tx.bus_date}</SYS_DATE><SYS_TIME>{tx.bus_time}</SYS_TIME><TX_ID>{ref.get('TX_ID', '')}</TX_ID><BILL_AMT>{ref.get('BILL_AMT', '')}</BILL_AMT><ROUND_BILL_AMT>{ref.get('BILL_AMT', '')}</ROUND_BILL_AMT><VAT_AMT>{tx.store.vat_amt}</VAT_AMT><PAYMENT_TYPE>001</PAYMENT_TYPE><CANCEL_ID></CANCEL_ID></DATA></SERVICE_BOX></HQ_REQUEST>"""

    @staticmethod
    def build_or_cancel(tx: TransactionContext) -> str:
        ref = tx.ref_data
        return f"""<?xml version="1.0" encoding="UTF-8"?><HQ_REQUEST><SERVICE_BOX><ADDRESS><VENDOR_ID>{tx.store.vendor_id}</VENDOR_ID><SERVICE_ID>{tx.store.service_id}</SERVICE_ID><METHOD>ORCancel</METHOD></ADDRESS><DATA><PAYMENT_CHANNEL>{tx.store.payment_channel}</PAYMENT_CHANNEL><VENDOR_ID>{ref.get('VENDOR_ID', '')}</VENDOR_ID><SERVICE_ID>{ref.get('SERV_ID', '')}</SERVICE_ID><SERV_ID>{ref.get('SERV_ID', '')}</SERV_ID><STORE_ID>{tx.store.store_id}</STORE_ID><STATION_ID>1</STATION_ID><BUS_DATE>{tx.bus_date}</BUS_DATE><BUS_TIME>{tx.bus_time}</BUS_TIME><TX_ID>{ref.get('TX_ID', '')}</TX_ID><PAYMENT_TYPE>001</PAYMENT_TYPE><CANCEL_ID></CANCEL_ID></DATA></SERVICE_BOX></HQ_REQUEST>"""

    @staticmethod
    def build_or_confirm(tx: TransactionContext) -> str:
        ref = tx.ref_data
        return f"""<?xml version="1.0" encoding="UTF-8"?><HQ_REQUEST><SERVICE_BOX><ADDRESS><VENDOR_ID>{tx.store.vendor_id}</VENDOR_ID><SERVICE_ID>{tx.store.service_id}</SERVICE_ID><METHOD>ORConfirm</METHOD></ADDRESS><DATA><PAYMENT_CHANNEL>{tx.store.payment_channel}</PAYMENT_CHANNEL><VENDOR_ID>{ref.get('VENDOR_ID', '')}</VENDOR_ID><SERVICE_ID>{ref.get('SERV_ID', '')}</SERVICE_ID><SERV_ID>{ref.get('SERV_ID', '')}</SERV_ID><STATION_ID>1</STATION_ID><STORE_ID>{tx.store.store_id}</STORE_ID><BUS_DATE>{tx.bus_date}</BUS_DATE><BUS_TIME>{tx.bus_time}</BUS_TIME><BILL_AMT>{ref.get('BILL_AMT', '')}</BILL_AMT><ROUND_BILL_AMT>{ref.get('BILL_AMT', '')}</ROUND_BILL_AMT><VAT_AMT>{tx.store.vat_amt}</VAT_AMT><TX_ID>{ref.get('TX_ID', '')}</TX_ID><SEQ_NO>{ref.get('SUM_SEQ', '')}</SEQ_NO><CLIENT_SERV_SEQ>{ref.get('SUM_SEQ', '')}</CLIENT_SERV_SEQ><SERV_ID>{ref.get('SERV_ID', '')}</SERV_ID><DATA_1>{ref.get('DATA_1', '')}</DATA_1><DATA_2>{ref.get('DATA_2', '')}</DATA_2><DATA_3>{ref.get('DATA_3', '')}</DATA_3><DATA_4>{ref.get('DATA_4', '')}</DATA_4><DATA_5>{ref.get('DATA_5', '')}</DATA_5><DATA_6>{ref.get('DATA_6', '')}</DATA_6><DATA_7>{ref.get('DATA_7', '')}</DATA_7><DATA_9>{ref.get('DATA_9', '')}</DATA_9><ZONE>{tx.store.zone}</ZONE><PAYMENT_TYPE>001</PAYMENT_TYPE><TOT_BILL_TRANS></TOT_BILL_TRANS><TOT_BILL_AMT></TOT_BILL_AMT><TOT_VENDOR_TRANS></TOT_VENDOR_TRANS><TOT_VENDOR_AMT></TOT_VENDOR_AMT><TOT_COUNTER_TRANS></TOT_COUNTER_TRANS><TOT_COUNTER_AMT></TOT_COUNTER_AMT><TOT_CLIENT_TRANS></TOT_CLIENT_TRANS><TOT_CLIENT_AMT></TOT_CLIENT_AMT><TOT_BILL_TRANS_OR></TOT_BILL_TRANS_OR><TOT_BILL_AMT_OR></TOT_BILL_AMT_OR><CANCEL_ID></CANCEL_ID></DATA></SERVICE_BOX></HQ_REQUEST>"""

    @staticmethod
    def build_amt_confirm(tx: TransactionContext) -> str:
        ref = tx.ref_data
        return f"""<?xml version="1.0" encoding="UTF-8"?><HQ_REQUEST><SERVICE_BOX><ADDRESS><VENDOR_ID>{tx.store.vendor_id}</VENDOR_ID><SERVICE_ID>{tx.store.service_id}</SERVICE_ID><METHOD>DataExchangeConfirm</METHOD></ADDRESS><DATA><PAYMENT_CHANNEL>{tx.store.payment_channel}</PAYMENT_CHANNEL><VENDOR_ID>{ref.get('VENDOR_ID', '')}</VENDOR_ID><SERV_ID>{ref.get('SERV_ID', '')}</SERV_ID><SERVICE_ID>{ref.get('SERV_ID', '')}</SERVICE_ID><STATION_ID>1</STATION_ID><STORE_ID>{tx.store.store_id}</STORE_ID><BUS_DATE>{tx.bus_date}</BUS_DATE><BUS_TIME>{tx.bus_time}</BUS_TIME><SYS_DATE>{tx.bus_date}</SYS_DATE><SYS_TIME>{tx.bus_time}</SYS_TIME><TX_ID>{ref.get('TX_ID', '')}</TX_ID><SEQ_NO>{ref.get('SEQ_NO', '')}</SEQ_NO><EMPLOYEE_ID>{tx.store.employee_id}</EMPLOYEE_ID><CLIENT_SERV_SEQ>{ref.get('SEQ_NO', '')}</CLIENT_SERV_SEQ><SERV_ID>{tx.store.service_id}</SERV_ID><BILL_AMT>{ref.get('SUM_AMT', '')}</BILL_AMT><ROUND_BILL_AMT>{ref.get('SUM_AMT', '')}</ROUND_BILL_AMT><ACCT_NO></ACCT_NO><VAT_AMT>{tx.store.vat_amt}</VAT_AMT><DATA_1>{ref.get('DATA_1', '')}</DATA_1><DATA_2>{ref.get('DATA_2', '')}</DATA_2><DATA_3>{ref.get('DATA_3', '')}</DATA_3><DATA_4>{ref.get('DATA_4', '')}</DATA_4><DATA_5>{ref.get('DATA_5', '')}</DATA_5><DATA_6>{ref.get('DATA_6', '')}</DATA_6><DATA_7>{ref.get('DATA_7', '')}</DATA_7><DATA_9>{ref.get('DATA_9', '')}</DATA_9><ZONE>{tx.store.zone}</ZONE><PAYMENT_TYPE>001</PAYMENT_TYPE><TOT_BILL_TRANS></TOT_BILL_TRANS><TOT_BILL_AMT></TOT_BILL_AMT><TOT_VENDOR_TRANS></TOT_VENDOR_TRANS><TOT_VENDOR_AMT></TOT_VENDOR_AMT><TOT_COUNTER_TRANS></TOT_COUNTER_TRANS><TOT_COUNTER_AMT></TOT_COUNTER_AMT><TOT_CLIENT_TRANS></TOT_CLIENT_TRANS><TOT_CLIENT_AMT></TOT_CLIENT_AMT><TOT_BILL_TRANS_OR></TOT_BILL_TRANS_OR><TOT_BILL_AMT_OR></TOT_BILL_AMT_OR><CANCEL_ID></CANCEL_ID><CANCEL_ID></CANCEL_ID><CUST_NAME>{ref.get('CUST_NAME', '')}</CUST_NAME><CUST_ADDR_1>{ref.get('CUST_ADDR_1', '')}</CUST_ADDR_1><CUST_ADDR_2>{ref.get('CUST_ADDR_2', '')}</CUST_ADDR_2><CUST_ADDR_3>{ref.get('CUST_ADDR_3', '')}</CUST_ADDR_3><CUST_PHONE_NO>{ref.get('CUST_PHONE_NO', '')}</CUST_PHONE_NO></DATA></SERVICE_BOX></HQ_REQUEST>"""

    @staticmethod
    def build_std_tk_inquiry(tx: TransactionContext) -> str:
        return f"""<?xml version="1.0" encoding="UTF-8"?><HQ_REQUEST><SERVICE_BOX><ADDRESS><VENDOR_ID>{tx.store.vendor_id}</VENDOR_ID><SERVICE_ID>{tx.store.service_id}</SERVICE_ID><METHOD>StdTkInquiry</METHOD></ADDRESS><DATA><PAYMENT_CHANNEL>{tx.store.payment_channel}</PAYMENT_CHANNEL><VENDOR_ID>{tx.store.vendor_id}</VENDOR_ID><SERV_ID>{tx.store.service_id}</SERV_ID><SERVICE_ID>{tx.store.service_id}</SERVICE_ID><STORE_ID>{tx.store.store_id}</STORE_ID><STATION_ID>1</STATION_ID><BUS_DATE>{tx.bus_date}</BUS_DATE><BUS_TIME>{tx.bus_time}</BUS_TIME><SYS_DATE>{tx.bus_date}</SYS_DATE><SYS_TIME>{tx.bus_time}</SYS_TIME><COMMON_TRN_ID>{tx.common_trn_id}</COMMON_TRN_ID><SEQ_NO></SEQ_NO><CLIENT_SERV_SEQ></CLIENT_SERV_SEQ><SHIFT_ID></SHIFT_ID><TRANS_TYPE></TRANS_TYPE><ACCT_NO></ACCT_NO><BILL_AMT>{tx.bill.bill_amt}</BILL_AMT><ROUND_BILL_AMT>{tx.bill.bill_amt}</ROUND_BILL_AMT><VAT_AMT>{tx.store.vat_amt}</VAT_AMT><REPT_TYPE>{tx.store.rept_type}</REPT_TYPE><REPT_NO></REPT_NO><PREV_REF_SEQ></PREV_REF_SEQ><PREV_REF_DATE></PREV_REF_DATE><SERV_CHARGE_NO></SERV_CHARGE_NO><ITEM_NAME>{tx.store.item_name}</ITEM_NAME><ITEM_SELECTION></ITEM_SELECTION><EMPLOYEE_ID>{tx.store.employee_id}</EMPLOYEE_ID><POS_TAX_ID>{tx.store.pos_tax_id}</POS_TAX_ID><DATA_1>{tx.data_1}</DATA_1><DATA_2>{tx.data_2}</DATA_2><DATA_3>{tx.data_3}</DATA_3><DATA_4>{tx.data_4}</DATA_4><DATA_5>{tx.data_5}</DATA_5><DATA_6>{tx.data_6}</DATA_6><DATA_7>{tx.data_7}</DATA_7><DATA_9>{tx.data_9}</DATA_9><ZONE>{tx.store.zone}</ZONE><PAYMENT_TYPE>001</PAYMENT_TYPE><CANCEL_ID></CANCEL_ID><CUST_NAME>{tx.customer.name}</CUST_NAME><CUST_ADDR_1>{tx.customer.addr_1}</CUST_ADDR_1><CUST_ADDR_2>{tx.customer.addr_2}</CUST_ADDR_2><CUST_ADDR_3>{tx.customer.addr_3}</CUST_ADDR_3><CUST_PHONE_NO>{tx.customer.phone_no}</CUST_PHONE_NO></DATA></SERVICE_BOX></HQ_REQUEST>"""

    @staticmethod
    def build_inquiry(tx: TransactionContext) -> str:
        return f"""<?xml version="1.0" encoding="UTF-8"?><HQ_REQUEST><SERVICE_BOX><ADDRESS><VENDOR_ID>{tx.store.vendor_id}</VENDOR_ID><SERVICE_ID>{tx.store.service_id}</SERVICE_ID><METHOD>Inquiry</METHOD></ADDRESS><DATA><PAYMENT_CHANNEL>{tx.store.payment_channel}</PAYMENT_CHANNEL><VENDOR_ID>{tx.store.vendor_id}</VENDOR_ID><SERV_ID>{tx.store.service_id}</SERV_ID><SERVICE_ID>{tx.store.service_id}</SERVICE_ID><STORE_ID>{tx.store.store_id}</STORE_ID><STATION_ID>1</STATION_ID><BUS_DATE>{tx.bus_date}</BUS_DATE><BUS_TIME>{tx.bus_time}</BUS_TIME><SYS_DATE>{tx.bus_date}</SYS_DATE><SYS_TIME>{tx.bus_time}</SYS_TIME><COMMON_TRN_ID>{tx.common_trn_id}</COMMON_TRN_ID><SEQ_NO/><CLIENT_SERV_SEQ/><SHIFT_ID></SHIFT_ID><TRANS_TYPE>N</TRANS_TYPE><ACCT_NO/><BILL_AMT>{tx.bill.bill_amt}</BILL_AMT><ROUND_BILL_AMT/><VAT_AMT>{tx.store.vat_amt}</VAT_AMT><REPT_TYPE>{tx.store.rept_type}</REPT_TYPE><REPT_NO/><PREV_REF_SEQ/><PREV_REF_DATE/><SERV_CHARGE_NO/><ITEM_NAME>{tx.store.item_name}</ITEM_NAME><ITEM_SELECTION>N</ITEM_SELECTION><EMPLOYEE_ID>{tx.store.employee_id}</EMPLOYEE_ID><POS_TAX_ID/><DATA_1>{tx.data_1}</DATA_1><DATA_2>{tx.data_2}</DATA_2><DATA_3>{tx.data_3}</DATA_3><DATA_4>{tx.data_4}</DATA_4><DATA_5>{tx.data_5}</DATA_5><DATA_6>{tx.data_6}</DATA_6><DATA_7>{tx.data_7}</DATA_7><DATA_9>{tx.data_9}</DATA_9><ZONE>{tx.store.zone}</ZONE><PAYMENT_TYPE>001</PAYMENT_TYPE><CANCEL_ID/></DATA></SERVICE_BOX></HQ_REQUEST>"""
