version: 0.0.5

services:
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    restart: unless-stopped 
    hostname: value-env.promotion-cs
    ports:
      - "8200:8200"
    env_file:
      - ./../production.env
    command: vault server -dev

  backends:
    build: 
      context: ..
      dockerfile: docker/Dockerfile.backend
      tags:
        - "nakarinsu/api_promotion:v1.0.3"
    image: nakarinsu/api_promotion:v1.0.3
    pull_policy: build
    platform: linux/amd64
    hostname: api.promotion-cs
    container_name: api
    restart: unless-stopped 
    env_file:
      - ./../production.env
    labels:
      - portless.name=api
    ports:
      - "8001:8000"
    volumes:
      - backend_data:/var/opt/backends
    # networks:
    #   - promotion-test_bridge_network
    network_mode: host

    stop_grace_period: 30s
    
  frontends:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
      tags:
        - "nakarinsu/web_promotion:v1.0.3"
    image: nakarinsu/web_promotion:v1.0.3
    pull_policy: build
    container_name: web
    platform: linux/amd64
    hostname: web.promotion-cs
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - frontend_data:/var/opt/frontends 
      - D:/Docker_Data/nginx/log:/var/log/nginx
    # networks:
    #   - promotion-test_bridge_network
    network_mode: host

  minios:
    image: minio/minio:latest
    pull_policy: always
    container_name: minio_servers
    hostname: minios.promotion-cs
    restart: always
    env_file:
      - ./../production.env
    command: server /data/local-bucket-share --console-address ":9001"
    ports:
      - "9000:9000" 
      - "9001:9001" 
      
    volumes:
      - data_center:/data                
      - D:/Docker_Data/minio/share:/data/local-bucket-share 

    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
  
    networks:
      - promotion-test_bridge_network

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: unless-stopped
    hostname: postgres.promotion-cs

    env_file:
      - ./../production.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data 
      - D:/Docker_Data/postgres/data:/var/opt/postgres
   
    networks:
      - promotion-test_bridge_network


networks:
  promotion-test_bridge_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16

volumes:
  postgres_data:
  mssql_data:
  data_center:
  frontend_data:
  backend_data:
