

FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

ENV APP_ENV=production
ENV APIPORT=8001
ENV WORKERS=2

RUN apt-get update && apt-get install -y \
    curl \
    gnupg2 \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

# 3. Microsoft ODBC for MSSQL

RUN curl -fsSL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor -o /usr/share/keyrings/microsoft-prod.gpg \
    && curl https://packages.microsoft.com/config/debian/12/prod.list > /etc/apt/sources.list.d/mssql-release.list

RUN apt-get update && ACCEPT_EULA=Y apt-get install -y \
    msodbcsql17 \
    mtools \
    unixodbc-dev \
    && rm -rf /var/lib/apt/lists/*



WORKDIR /app

# 4. Python Dependencies
COPY ./docs/requirements.txt .
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir --root-user-action=ignore  -r requirements.txt

# 5. Application Source & Scripts
COPY ./app ./app
# สมมติว่าเก็บ script backup ไว้ใน app/scripts
# RUN chmod +x /app/app/scripts/backup_logic.py 

EXPOSE 8000

# 6. Entrypoint (เพื่อรันทั้ง API และเช็คระบบ Backup)
CMD ["python", "-m", "app.backend.main"]