FROM node:20-alpine AS build-stage
WORKDIR /app
COPY ./webpack/package.json ./
RUN npm install
COPY ./webpack .
RUN npm run build

# Stage 2: Serve

FROM nginx:stable-alpine

COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf


COPY --from=build-stage /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]


